#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$ROOT_DIR"

if [[ "$(id -u)" -ne 0 ]]; then
  echo "This project is designed to be started with sudo for the final sysctl applier."
  echo "Run: sudo ./start.sh"
  exit 1
fi

export AI_NET_TUNER_ROOT="$ROOT_DIR"
export UV_CACHE_DIR="${UV_CACHE_DIR:-$ROOT_DIR/.cache/uv}"
export HF_HOME="${HF_HOME:-$ROOT_DIR/.cache/huggingface}"
export AI_NET_TUNER_DEVICE="${AI_NET_TUNER_DEVICE:-auto}"

CALLER_HOME="${HOME:-}"
if [[ -n "${SUDO_USER:-}" ]] && command -v getent >/dev/null 2>&1; then
  CALLER_HOME="$(getent passwd "$SUDO_USER" | cut -d: -f6)"
fi
DEFAULT_LLAMA_CPP_DIR="$ROOT_DIR/vendor/llama.cpp"
if [[ -n "$CALLER_HOME" ]] && [[ -f "$CALLER_HOME/llama.cpp/CMakeLists.txt" ]]; then
  DEFAULT_LLAMA_CPP_DIR="$CALLER_HOME/llama.cpp"
fi

export LLAMA_CPP_DIR="${LLAMA_CPP_DIR:-$DEFAULT_LLAMA_CPP_DIR}"
export LLAMA_CPP_BUILD_DIR="${LLAMA_CPP_BUILD_DIR:-$LLAMA_CPP_DIR/build}"
export AI_NET_TUNER_LLAMA_MODEL="${AI_NET_TUNER_LLAMA_MODEL:-bartowski/Qwen_Qwen3-1.7B-GGUF:Q5_K_M}"
export AI_NET_TUNER_LLAMA_MODEL_FILE="${AI_NET_TUNER_LLAMA_MODEL_FILE:-}"
export AI_NET_TUNER_LLAMA_HOST="${AI_NET_TUNER_LLAMA_HOST:-127.0.0.1}"
export AI_NET_TUNER_LLAMA_PORT="${AI_NET_TUNER_LLAMA_PORT:-8080}"
export AI_NET_TUNER_LLAMA_CTX_SIZE="${AI_NET_TUNER_LLAMA_CTX_SIZE:-32768}"
export AI_NET_TUNER_LLAMA_PARALLEL="${AI_NET_TUNER_LLAMA_PARALLEL:-1}"
export AI_NET_TUNER_LLAMA_BATCH_SIZE="${AI_NET_TUNER_LLAMA_BATCH_SIZE:-128}"
export AI_NET_TUNER_LLAMA_UBATCH_SIZE="${AI_NET_TUNER_LLAMA_UBATCH_SIZE:-128}"
export AI_NET_TUNER_LLAMA_GPU_LAYERS="${AI_NET_TUNER_LLAMA_GPU_LAYERS:-99}"
export AI_NET_TUNER_PROMPT_KEY_LIMIT="${AI_NET_TUNER_PROMPT_KEY_LIMIT:-80}"
export AI_NET_TUNER_PROMPT_DOC_LIMIT="${AI_NET_TUNER_PROMPT_DOC_LIMIT:-60}"
export AI_NET_TUNER_MAX_PROPOSALS_PER_CYCLE="${AI_NET_TUNER_MAX_PROPOSALS_PER_CYCLE:-2}"
export AI_NET_TUNER_QWEN_MAX_TOKENS="${AI_NET_TUNER_QWEN_MAX_TOKENS:-640}"
export AI_NET_TUNER_QWEN_TEMPERATURE="${AI_NET_TUNER_QWEN_TEMPERATURE:-0.30}"
export AI_NET_TUNER_QWEN_TOP_P="${AI_NET_TUNER_QWEN_TOP_P:-0.85}"
export GGML_CUDA_ENABLE_UNIFIED_MEMORY="${GGML_CUDA_ENABLE_UNIFIED_MEMORY:-1}"

if [[ "$AI_NET_TUNER_DEVICE" == "cpu" ]]; then
  export CUDA_VISIBLE_DEVICES=""
  AI_NET_TUNER_LLAMA_GPU_LAYERS=0
fi

LLAMA_SERVER_URL="http://${AI_NET_TUNER_LLAMA_HOST}:${AI_NET_TUNER_LLAMA_PORT}"
QWEN_ENDPOINT="${LLAMA_SERVER_URL}/v1/chat/completions"
LLAMA_LOG_DIR="$ROOT_DIR/state/llama"
LLAMA_LOG_FILE="$LLAMA_LOG_DIR/llama-server.log"
LLAMA_PID=""
LLAMA_SERVER_BIN_RESOLVED=""
LLAMA_MODEL_FILE_RESOLVED=""

echo "────────────────────────────────────────"
echo "AI Net Tuner"
echo "Traffic Model A dataset:"
echo "  GÉANT Backbone Network traffic matrix dataset"
echo "  public source: https://github.com/duchuyle108/SDN-TMprediction"
echo "  original family: GÉANT/Abilene traffic matrix traces"
echo "Qwen Model B:"
echo "  $AI_NET_TUNER_LLAMA_MODEL via llama.cpp endpoint"
echo "  device: $AI_NET_TUNER_DEVICE, gpu layers: $AI_NET_TUNER_LLAMA_GPU_LAYERS"
echo "  ctx: $AI_NET_TUNER_LLAMA_CTX_SIZE, parallel: $AI_NET_TUNER_LLAMA_PARALLEL, batch: $AI_NET_TUNER_LLAMA_BATCH_SIZE, ubatch: $AI_NET_TUNER_LLAMA_UBATCH_SIZE"
echo "  bounded proposals: max=$AI_NET_TUNER_MAX_PROPOSALS_PER_CYCLE, prompt_keys=$AI_NET_TUNER_PROMPT_KEY_LIMIT, docs=$AI_NET_TUNER_PROMPT_DOC_LIMIT, max_tokens=$AI_NET_TUNER_QWEN_MAX_TOKENS"
echo "  llama.cpp: $LLAMA_CPP_DIR"
echo "Human-in-the-loop:"
echo "  Korean warning text is generated by the agent policy layer"
echo "  y/n only, timeout -> n"
echo "────────────────────────────────────────"

if ! command -v uv >/dev/null 2>&1; then
  echo "uv is required. Install uv first: https://docs.astral.sh/uv/"
  exit 1
fi

if ! command -v curl >/dev/null 2>&1; then
  echo "curl is required for llama-server health checks."
  exit 1
fi

stop_llama_server() {
  if [[ -n "$LLAMA_PID" ]] && kill -0 "$LLAMA_PID" >/dev/null 2>&1; then
    echo "llama-server 종료 중..."
    kill -TERM "$LLAMA_PID" >/dev/null 2>&1 || true
    for _ in $(seq 1 20); do
      if ! kill -0 "$LLAMA_PID" >/dev/null 2>&1; then
        wait "$LLAMA_PID" 2>/dev/null || true
        LLAMA_PID=""
        return 0
      fi
      sleep 0.5
    done
    echo "llama-server가 정상 종료되지 않아 강제 종료합니다."
    kill -KILL "$LLAMA_PID" >/dev/null 2>&1 || true
    wait "$LLAMA_PID" 2>/dev/null || true
    LLAMA_PID=""
  fi
}

cleanup() {
  stop_llama_server
}
trap cleanup EXIT
trap 'stop_llama_server; exit 130' INT
trap 'stop_llama_server; exit 143' TERM

find_llama_server_bin() {
  if [[ -n "${LLAMA_SERVER_BIN:-}" ]] && [[ -x "$LLAMA_SERVER_BIN" ]]; then
    printf '%s\n' "$LLAMA_SERVER_BIN"
    return 0
  fi

  if command -v llama-server >/dev/null 2>&1; then
    command -v llama-server
    return 0
  fi

  for candidate in \
    "$CALLER_HOME/llama.cpp/build/bin/llama-server" \
    "$CALLER_HOME/llama.cpp/build/bin/Release/llama-server" \
    "$LLAMA_CPP_BUILD_DIR/bin/llama-server" \
    "$LLAMA_CPP_BUILD_DIR/bin/Release/llama-server" \
    "$LLAMA_CPP_BUILD_DIR/examples/server/llama-server" \
    "$LLAMA_CPP_BUILD_DIR/llama-server"; do
    if [[ -x "$candidate" ]]; then
      printf '%s\n' "$candidate"
      return 0
    fi
  done

  return 1
}

print_llama_cpp_install_guide() {
  cat <<EOF

llama.cpp 설치가 필요합니다.

이 스크립트는 SSD 중복 사용을 피하기 위해 llama.cpp를 자동으로 clone/build하지 않습니다.
이미 설치했다면 아래 둘 중 하나로 경로를 알려주세요.

1) 실행 때 직접 지정:
   sudo env LLAMA_SERVER_BIN=$CALLER_HOME/llama.cpp/build/bin/llama-server ./start.sh

2) PATH에 추가:
   export PATH="$CALLER_HOME/llama.cpp/build/bin:\$PATH"
   sudo env PATH="\$PATH" ./start.sh

아직 설치하지 않았다면 한 번만 설치하세요.

   cd $CALLER_HOME
   git clone https://github.com/ggml-org/llama.cpp
   cd llama.cpp
   cmake -S . -B build \\
     -DCMAKE_BUILD_TYPE=Release \\
     -DGGML_CUDA=ON \\
     -DCMAKE_CUDA_ARCHITECTURES=75 \\
     -DCMAKE_CUDA_HOST_COMPILER=/usr/bin/g++-15 \\
     -DCMAKE_CXX_COMPILER=/usr/bin/g++-15
   cmake --build build --config Release --target llama-server -j "\$(nproc)"

GTX 1660 Super는 CUDA architecture 75를 사용합니다.
현재 PC처럼 nvcc 13.x와 기본 g++ 16 조합이 깨지는 경우가 있어 g++-15를 권장합니다.
CPU 전용으로 빌드하려면 -DGGML_CUDA=OFF 로 빌드해도 됩니다.

EOF
}

require_llama_server() {
  if LLAMA_SERVER_BIN_RESOLVED="$(find_llama_server_bin)"; then
    echo "llama-server: $LLAMA_SERVER_BIN_RESOLVED"
    return 0
  fi

  print_llama_cpp_install_guide
  exit 1
}

find_llama_model_file() {
  if [[ -n "$AI_NET_TUNER_LLAMA_MODEL_FILE" ]] && [[ -f "$AI_NET_TUNER_LLAMA_MODEL_FILE" ]]; then
    printf '%s\n' "$AI_NET_TUNER_LLAMA_MODEL_FILE"
    return 0
  fi

  local model_cache="$HF_HOME/hub/models--bartowski--Qwen_Qwen3-1.7B-GGUF"
  if [[ -d "$model_cache" ]]; then
    local found
    found="$(find "$model_cache" -name '*Q5_K_M.gguf' -print -quit 2>/dev/null || true)"
    if [[ -n "$found" ]] && [[ -f "$found" ]]; then
      printf '%s\n' "$found"
      return 0
    fi
  fi

  return 1
}

gpu_runtime_available() {
  if [[ "$AI_NET_TUNER_DEVICE" == "cpu" ]]; then
    return 1
  fi
  if ! command -v nvidia-smi >/dev/null 2>&1; then
    return 1
  fi
  nvidia-smi >/dev/null 2>&1
}

llama_device_available() {
  if [[ "$AI_NET_TUNER_DEVICE" == "cpu" ]]; then
    return 1
  fi
  local devices
  devices="$("$LLAMA_SERVER_BIN_RESOLVED" --list-devices 2>/dev/null | awk 'NR > 1 && NF { print }' || true)"
  [[ -n "$devices" ]]
}

start_llama_server() {
  local gpu_layers="$1"
  local model_args=()
  if [[ -n "$LLAMA_MODEL_FILE_RESOLVED" ]]; then
    model_args=(-m "$LLAMA_MODEL_FILE_RESOLVED")
  else
    model_args=(-hf "$AI_NET_TUNER_LLAMA_MODEL")
  fi

  "$LLAMA_SERVER_BIN_RESOLVED" \
    "${model_args[@]}" \
    --host "$AI_NET_TUNER_LLAMA_HOST" \
    --port "$AI_NET_TUNER_LLAMA_PORT" \
    --ctx-size "$AI_NET_TUNER_LLAMA_CTX_SIZE" \
    --parallel "$AI_NET_TUNER_LLAMA_PARALLEL" \
    --n-gpu-layers "$gpu_layers" \
    --batch-size "$AI_NET_TUNER_LLAMA_BATCH_SIZE" \
    --ubatch-size "$AI_NET_TUNER_LLAMA_UBATCH_SIZE" \
    --jinja \
    >"$LLAMA_LOG_FILE" 2>&1 &
  LLAMA_PID="$!"
}

wait_for_llama_server() {
  for _ in $(seq 1 120); do
    if ! kill -0 "$LLAMA_PID" >/dev/null 2>&1; then
      return 1
    fi
    if curl -fsS "$LLAMA_SERVER_URL/health" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

echo "[1/5] Syncing Python environment"
uv sync

echo "[2/5] Preparing public GÉANT dataset"
uv run ai-net-tuner prepare-dataset

echo "[3/5] Preparing trained traffic forecaster"
if [[ ! -f "$ROOT_DIR/models/traffic_forecaster_geant.npz" ]]; then
  uv run ai-net-tuner train-forecaster --download
else
  echo "Forecaster already exists: models/traffic_forecaster_geant.npz"
fi

echo "[4/5] Preparing and starting Qwen3-1.7B Q5_K_M llama.cpp server"
mkdir -p "$LLAMA_LOG_DIR"
if curl -fsS "$LLAMA_SERVER_URL/health" >/dev/null 2>&1; then
  echo "Existing llama-server is already healthy: $LLAMA_SERVER_URL"
else
  require_llama_server
  if LLAMA_MODEL_FILE_RESOLVED="$(find_llama_model_file)"; then
    echo "llama model file: $LLAMA_MODEL_FILE_RESOLVED"
  else
    echo "llama model source: $AI_NET_TUNER_LLAMA_MODEL"
  fi

  if [[ "$AI_NET_TUNER_LLAMA_GPU_LAYERS" != "0" ]] && ! llama_device_available; then
    echo "llama.cpp에서 사용할 CUDA device/backend를 찾지 못했습니다. CPU로 시작합니다."
    echo "GTX 1660 Super GPU offload를 쓰려면 llama.cpp를 GGML_CUDA=ON, CMAKE_CUDA_ARCHITECTURES=75로 다시 빌드해야 합니다."
    AI_NET_TUNER_LLAMA_GPU_LAYERS=0
    export CUDA_VISIBLE_DEVICES=""
  elif [[ "$AI_NET_TUNER_LLAMA_GPU_LAYERS" != "0" ]] && ! gpu_runtime_available; then
    echo "nvidia-smi는 실패했지만 llama.cpp device는 감지됐습니다. GPU로 먼저 시도합니다."
  fi

  if [[ "$AI_NET_TUNER_LLAMA_GPU_LAYERS" != "0" ]]; then
    echo "llama.cpp devices:"
    "$LLAMA_SERVER_BIN_RESOLVED" --list-devices || true
  fi

  if [[ "$AI_NET_TUNER_LLAMA_GPU_LAYERS" == "0" ]]; then
    AI_NET_TUNER_LLAMA_GPU_LAYERS=0
    export CUDA_VISIBLE_DEVICES=""
  fi

  start_llama_server "$AI_NET_TUNER_LLAMA_GPU_LAYERS"
  if wait_for_llama_server; then
    echo "llama-server ready: $LLAMA_SERVER_URL"
  elif [[ "$AI_NET_TUNER_LLAMA_GPU_LAYERS" != "0" ]] && [[ "$AI_NET_TUNER_DEVICE" == "auto" ]]; then
    echo "llama-server failed with GPU. Retrying on CPU. Last GPU log:"
    tail -80 "$LLAMA_LOG_FILE" || true
    stop_llama_server
    LLAMA_PID=""
    AI_NET_TUNER_LLAMA_GPU_LAYERS=0
    export CUDA_VISIBLE_DEVICES=""
    start_llama_server 0
    if wait_for_llama_server; then
      echo "llama-server ready on CPU: $LLAMA_SERVER_URL"
    else
      echo "llama-server did not become ready on CPU. Log:"
      tail -120 "$LLAMA_LOG_FILE" || true
      exit 1
    fi
  else
    echo "llama-server did not become ready. Log:"
    tail -120 "$LLAMA_LOG_FILE" || true
    exit 1
  fi
fi

echo "[5/5] Starting 3-minute proposal loop"
uv run ai-net-tuner run \
  --forecast-model geant \
  --qwen-mode endpoint \
  --qwen-endpoint "$QWEN_ENDPOINT" \
  --interval 180 \
  --timeout 150 \
  --apply \
  --print-model-info
